apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-deploy-yaml
  name: nginx-deploy-yaml
  namespace: default
spec:
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-deploy-yaml
  type: LoadBalancer
